<a href="https://colab.research.google.com/github/Marieta3/sentiment-analysis-russian/blob/master/sentiment_analiza.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Analiza sentimenta tvitova na ruskom jeziku


##Importovanje potrebnih biblioteka

In [0]:
import tensorflow as tf
import tflearn
import pandas as pd
import nltk 
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.snowball import RussianStemmer
from nltk.tokenize import TweetTokenizer
import re
from collections import Counter
from datetime import datetime
import numpy as np
from tflearn.data_utils import to_categorical

##Import za custom nn

In [0]:
from __future__ import print_function

from abc import abstractmethod
import math
import random
import copy

##Konstante

In [0]:
VOCAB_SIZE = 5000
MANJI_DEO = True
TEST_SIZE = 0.3

##Učitavanje podataka

In [0]:
col = 3 #kolona koja sadrzi tvit, ostale kolone nisu potrebne

if(MANJI_DEO):
  positive = pd.read_csv(
      'https://raw.githubusercontent.com/Marieta3/sentiment-analysis-russian/master/positive.csv', header=None, delimiter=';')[[col]].sample(40000);
  negative = pd.read_csv(
      'https://raw.githubusercontent.com/Marieta3/sentiment-analysis-russian/master/negative.csv', header=None, delimiter=';')[[col]].sample(40000);
else:
  positive = pd.read_csv(
      'https://raw.githubusercontent.com/Marieta3/sentiment-analysis-russian/master/positive.csv', header=None, delimiter=';')[[col]];
  negative = pd.read_csv(
      'https://raw.githubusercontent.com/Marieta3/sentiment-analysis-russian/master/negative.csv', header=None, delimiter=';')[[col]];  

##Testiranje učitanih podataka


In [6]:
print('Pozitivnih tvitova: ' +str(len(positive)))
print('Negativnih tvitova: ' +str(len(negative)))

#positive = positive.head(30000)
#negative = negative.head(30000)

print('Pozitivnih tvitova: ' +str(len(positive)))
print('Negativnih tvitova: ' +str(len(negative)))

Pozitivnih tvitova: 40000
Negativnih tvitova: 40000
Pozitivnih tvitova: 40000
Negativnih tvitova: 40000


##Izvlačenje osnovnog oblika iz tokena

In [7]:
stemmer = RussianStemmer()
stem_cache={}  #smanjuje vreme izvršavanja, ako se reč već pojavljivala, samo je uzmemo iz liste
def get_stem(token):
  stem =stem_cache.get(token, None)
  if stem:
    return stem
  
  token=re.sub('[^а-яА-Я ]', '', token)  #samo slova
  stem=stemmer.stem(token)
  stem_cache[token]=stem
  return stem
get_stem('!')

''

##Tokenizacija

In [0]:
recnik = Counter()
tokenizer = TweetTokenizer()
stop_words = stopwords.words('russian')

def popuni_recnik(tweets):
  for t in tweets.values.tolist():
    #print(t[0])
    tweet=t[0]
    
    tokens=tokenizer.tokenize(tweet)
    for token in tokens:
      stem=get_stem(token)
      if stem!='' and stem not in stop_words and token not in stop_words:
        recnik[stem]+=1
    
start_time=datetime.now()  
popuni_recnik(positive)
popuni_recnik(negative)
end_time=datetime.now()

In [9]:
print('Потребно време за попуњавање речника: ', end_time-start_time)
print("Укупан број различитих речи: ", len(recnik))


Потребно време за попуњавање речника:  0:00:39.302675
Укупан број различитих речи:  50473


In [0]:
vocab = sorted(recnik, key=recnik.get, reverse=True)[:VOCAB_SIZE]  #сортирано по броју понављања опадајуће, првих 5000

In [11]:
print(vocab[:10])
print(vocab[1000:1020])
print(vocab[-10:])
print("Дужина скраћеног речника: ",len(vocab))

['эт', 'сегодн', 'прост', 'мо', 'хоч', 'очен', 'ден', 'теб', 'буд', 'год']
['ссылк', 'перевод', 'теря', 'чтонибуд', 'херн', 'программ', 'событ', 'просмотр', 'возвраща', 'кошмар', 'длин', 'юм', 'ждет', 'дурацк', 'бед', 'жирн', 'клев', 'г', 'зло', 'официальн']
['хммм', 'сценар', 'выкинут', 'госпад', 'ущербн', 'проебыва', 'связыва', 'инвалид', 'грбан', 'троек']
Дужина скраћеног речника:  5000


In [15]:
idx=0
print("Reč: ", vocab[idx], " se pojavila ", recnik.get(vocab[idx]), " puta")




Reč:  эт  se pojavila  8056  puta


In [13]:
token_to_idx = {vocab[i] : i for i in range(VOCAB_SIZE)}
print(token_to_idx.get('', None))
print(type(token_to_idx))

None
<class 'dict'>


##Pretvaranje tvita u vektor

*   vektor je duzine broja reci u recniku (5000)
*   ukoliko tvit sadrzi rec koja se nalazi u recniku, na odgovarajucem mestu u vektoru se nalazi jedinica; u suprotnom nula


In [0]:
def tweet_to_vector(tweet, print_unknown=False):
  vector=np.zeros(VOCAB_SIZE, dtype=int)
  for token in tokenizer.tokenize(tweet):
    stem=get_stem(token)
    idx=token_to_idx.get(stem, None)
    if idx is not None:
      vector[idx]=1
    else:
      if(print_unknown):
        print('Nepoznata rec: ', token)
  return vector
    

In [17]:
tw_idx=1
pos_tws=positive.values.tolist()
neg_tws=negative.values.tolist()
print("tweet: {}".format(pos_tws[tw_idx][0]))
print("tweet: {}".format(tweet_to_vector(pos_tws[tw_idx][0])[:10]))
print("tweet: {}".format(neg_tws[tw_idx][0]))
print("tweet: {}".format(tweet_to_vector(neg_tws[tw_idx][0])[:10]))

tweet: Ребят, спасибо вам за шикарную ночь!!! Это было круто!) http://t.co/Tm44RpfXQG
tweet: [1 0 0 0 0 0 0 0 0 0]
tweet: Снег ты где ???:( хочется хоть чуть -чуть новогодней атмосферы !
tweet: [0 0 0 0 0 0 0 0 0 0]


In [18]:
try:
  del train_vectors
  del test_vectors
except:
  print('Nije definisano')
  
train_size = round((len(negative) + len(positive))*(1-TEST_SIZE))
test_size = len(negative) + len(positive) - train_size

train_vectors = np.zeros((train_size, VOCAB_SIZE), dtype=np.int_)
test_vectors = np.zeros((test_size, VOCAB_SIZE), dtype=np.int_)

Nije definisano


In [0]:
tweets=[]
cnt=0
cnt2=0

train_pos_size = round(len(positive)*(1-TEST_SIZE))
train_neg_size = round(len(negative)*(1-TEST_SIZE))

for tweet in negative.values.tolist():
  #print(tweet[0])
  tweets.append(tweet[0])
  if cnt < train_neg_size:
    train_vectors[cnt]=tweet_to_vector(tweet[0])
    cnt+=1
  else:
    test_vectors[cnt2]=tweet_to_vector(tweet[0])
    cnt2+=1
for tweet in positive.values.tolist():
  tweets.append(tweet[0])
  if cnt < train_neg_size + train_pos_size:
    train_vectors[cnt]=tweet_to_vector(tweet[0])
    cnt+=1
  else:
    test_vectors[cnt2]=tweet_to_vector(tweet[0])
    cnt2+=1


In [20]:
print(len(train_vectors))
print(len(train_vectors[0]))
print(train_vectors)

56000
5000
[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


##Brisanje vektora tvitova

In [0]:
del train_vectors
del test_vectors

##Labele

In [0]:
#labels = np.append(np.zeros(len(negative), dtype=np.int_), np.ones(len(positive), dtype=np.int_))

train_labels = np.append(
    np.zeros(train_neg_size, dtype=np.int_), 
    np.ones(train_pos_size, dtype=np.int_))

test_labels = np.append(
    np.zeros(len(negative) - train_neg_size, dtype=np.int_), 
    np.ones(len(positive) - train_pos_size, dtype=np.int_))

In [0]:
y_train = to_categorical(train_labels, 2)
y_test = to_categorical(test_labels, 2)


##Kreiranje modela

In [0]:
def build_model(learning_rate=0.1):
    tf.reset_default_graph()
    
    net = tflearn.input_data([None, VOCAB_SIZE])
    net = tflearn.fully_connected(net, 125, activation='ReLU')
    net = tflearn.fully_connected(net, 25, activation='ReLU')
    net = tflearn.fully_connected(net, 2, activation='softmax')
    regression = tflearn.regression(
        net, 
        optimizer='sgd', 
        learning_rate=learning_rate, 
        loss='categorical_crossentropy')
    
    model = tflearn.DNN(net)
    return model

In [23]:

model = build_model(learning_rate=0.75)

W0703 09:28:03.335266 140634864326528 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tflearn/layers/core.py:81: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0703 09:28:03.342907 140634864326528 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tflearn/initializations.py:174: calling TruncatedNormal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0703 09:28:03.406377 140634864326528 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tflearn/optimizers.py:135: The name tf.train.GradientDescentOptimizer is deprecated. Please use tf.compat.v1.train.GradientDescentOptimizer instead.

W0703 09:28:03.421644 140634864326528 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tflearn/objectives.py:66: c

In [67]:
model.fit(
    train_vectors, 
    y_train, 
    validation_set=0.1, 
    show_metric=True, 
    batch_size=128, 
    n_epoch=3)

Training Step: 13001  | total loss: 0.03872 | time: 7.572s
| SGD | epoch: 033 | loss: 0.03872 - acc: 0.9863 -- iter: 50304/50400
Training Step: 13002  | total loss: 0.03811 | time: 8.642s
| SGD | epoch: 033 | loss: 0.03811 - acc: 0.9861 | val_loss: 0.05570 - val_acc: 0.9770 -- iter: 50400/50400
--


##Testiranje

In [76]:
predictions = (np.array(model.predict(test_vectors))[:,0] >= 0.5).astype(np.int_)
accuracy = np.mean(predictions == y_test[:,0], axis=0)
print("Accuracy: ", accuracy)

Accuracy:  0.68175


In [0]:
def test_tweet(tweet):
    tweet_vector = tweet_to_vector(tweet, False)
    positive_prob = model.predict([tweet_vector])[0][1]
    print('Original tweet: {}'.format(tweet))
    print('P(positive) = {:.5f}. Result: '.format(positive_prob), 
          'Positive' if positive_prob > 0.5 else 'Negative')

In [0]:
def test_tweet_number(idx):
    test_tweet(tweets[idx])

In [1]:
test_tweet_number(40000-2)

NameError: ignored

##Proba

In [0]:
tweets_for_testing = [
    "меня оштрафовали по дороге домой!",
    "Я люблю мороженое!",
    "Я не люблю мороженое",
    "меня обманули",
    "меня обманули позитив",
    "меня он очень бесить",
    "меня он не бесить",
    "Почему по ночам мне не спится? У машины скрипит колесо. Отразилась луна в ягодице. 10 лет тебе,синяя птица! Жаль,что букв всего лишь сто со",
    "Смотрите сегодня, в 23:35, сразу после финала #голос6 @voice1tv, на @1tv, большой новогодний выпуск @vecherniy_urgant #вечернийургант! Я, @urgantcom и @lazarevsergey приготовили для вас праздничный новогодний номер!))) #иванургант #сергейлазарев #билан #… http://ift.tt/2zLgzWk ",
    "ШОК! Данилу Козловского задержали в центре Москвы за чтение Шекспира!",
    "Через час в Петербурге,на улице Рубинштейна,дом 23 откроют памятник Сергею Довлатову.Надеваем халаты,тапочки,берем собак и цветы!",
    "Спасибо академикам,коллегам и номинантам!Спасибо всей команде ВУ!Спасибо моей семье!И конечно спасибо Вам,дорогие телезрители!#тэфи2016",
    "А вот и ласточка-новостнуха!24 апреля в Крокусе я поделюсь с Вами инсайтом на Synergy Insight Forum. Приходите что ли! #sif2017"
]
for tweet in tweets_for_testing:
    test_tweet(tweet) 
    print("---------")

##Custom neuronska mreza

In [0]:

random.seed(1337)

class ComputationalNode(object):

    @abstractmethod
    def forward(self, x):
        pass

    @abstractmethod
    def backward(self, dz):
        pass
      
class MultiplyNode(ComputationalNode):

    def __init__(self):
        self.x = [0., 0.]  # x[0] je ulaz, x[1] je tezina

    def forward(self, x):
        self.x = x
        # TODO 1: implementirati forward-pass za mnozac
        #raise NotImplementedError('TODO 1')
        return self.x[0]*self.x[1]

    def backward(self, dz):
        # TODO 1: implementirati backward-pass za mnozac
        #raise NotImplementedError('TODO 1')
        return [dz*self.x[1], dz*self.x[0]]
      
class SumNode(ComputationalNode):

    def __init__(self):
        self.x = []  # x je vektor, odnosno niz skalara

    def forward(self, x):
        self.x = x
        # TODO 2: implementirati forward-pass za sabirac
        #raise NotImplementedError('TODO 2')
        return sum(self.x)

    def backward(self, dz):
        # TODO 2: implementirati backward-pass za sabirac
        #raise NotImplementedError('TODO 2')
        return [dz]*len(self.x)
      


In [0]:
class SigmoidNode(ComputationalNode):

    def __init__(self):
        self.x = 0.  # x je skalar

    def forward(self, x):
        self.x = x
        # TODO 3: implementirati forward-pass za sigmoidalni cvor
        #raise NotImplementedError('TODO 3')
        return self._sigmoid(self.x)

    def backward(self, dz):
        # TODO 3: implementirati backward-pass za sigmoidalni cvor
        #raise NotImplementedError('TODO 3')
        return dz*self._sigmoid(self.x)*(1-self._sigmoid(self.x))

    def _sigmoid(self, x):
        # TODO 3: implementirati sigmoidalnu funkciju
        #raise NotImplementedError('TODO 3')
        return 1/(1+math.exp(-x))

In [0]:
class ReLuNode(ComputationalNode):

    def __init__(self):
        self.x = 0.  # x je skalar

    def forward(self, x):
        self.x = x
        return self._relu(self.x)

    def backward(self, dz):
        if self.x > 0.:
            return dz*1.
        else:
            return dz*0.

    def _relu(self, x):
        return max(0., x)

In [0]:
class NeuronNode(ComputationalNode):

    def __init__(self, n_inputs, activation):
        self.n_inputs = n_inputs  # moramo da znamo kolika ima ulaza da bismo znali koliko nam treba mnozaca
        self.multiply_nodes = []  # lista mnozaca
        self.sum_node = SumNode()  # sabirac

        # TODO 4: napraviti n_inputs mnozaca u listi mnozaca, odnosno mnozac za svaki ulaz i njemu odgovarajucu tezinu
        # za svaki mnozac inicijalizovati tezinu na broj iz normalne (gauss) raspodele sa st. devijacijom 0.1
        for n in range(n_inputs):
            mn=MultiplyNode()
            mn.x=[1., random.gauss(0., 0.1)]
            self.multiply_nodes.append(mn)

        # TODO 5: dodati jos jedan mnozac u listi mnozaca, za bias
        # bias ulaz je uvek fiksiran na 1.
        # bias tezinu inicijalizovati na broj iz normalne (gauss) raspodele sa st. devijacijom 0.01
        bias=MultiplyNode()
        bias.x=[1., random.gauss(0., 0.01)]
        self.multiply_nodes.append(bias)

        # TODO 6: ako ulazni parametar funckije 'activation' ima vrednosti 'sigmoid',
        # inicijalizovati da aktivaciona funckija bude sigmoidalni cvor
        self.activation_node = None
        if activation=='sigmoid':
            self.activation_node=SigmoidNode()
        elif activation=='relu':
            self.activation_node=ReLuNode()
        self.previous_deltas=[0.]*(self.n_inputs+1)

        self.gradients = []

    def forward(self, x):  # x je vektor ulaza u neuron, odnosno lista skalara
        #x = copy.copy(x)
        x=np.append(x, 1.)  # uvek implicitino dodajemo bias=1. kao ulaz

        # TODO 7: implementirati forward-pass za vestacki neuron
        # u x se nalaze ulazi i bias neurona
        # iskoristi forward-pass za mnozace, sabirac i aktivacionu funkciju da bi se dobio konacni izlaz iz neurona
        for_sum=[]
        for i, xx in enumerate(x):
            inp=[x[i], self.multiply_nodes[i].x[1]]
            for_sum.append(self.multiply_nodes[i].forward(inp))
        summed=self.sum_node.forward(for_sum)
        summed_act=self.activation_node.forward(summed)
        return summed_act

    def backward(self, dz):
        dw = []
        d = dz[0] if type(dz[0]) == float else sum(dz)  # u d se nalazi spoljasnji gradijent izlaza neurona

        # TODO 8: implementirati backward-pass za vestacki neuron
        # iskoristiti backward-pass za aktivacionu funkciju, sabirac i mnozace da bi se dobili gradijenti tezina neurona
        # izracunate gradijente tezina ubaciti u listu dw
        d=self.activation_node.backward(d)
        d=self.sum_node.backward(d)
        for i, dd in enumerate(d):
            dw.append(self.multiply_nodes[i].backward(dd)[1])
        self.gradients.append(dw)
        return dw

    def update_weights(self, learning_rate, momentum):
        # azuriranje tezina vestackog neurona
        # learning_rate je korak gradijenta

        # TODO 11: azurirati tezine neurona (odnosno azurirati drugi parametar svih mnozaca u neuronu)
        # gradijenti tezina se nalaze u list self.gradients
        #raise NotImplementedError('TODO 11')
        for i, multiply_node in enumerate(self.multiply_nodes):
            mean_gradient=sum([grad[i] for grad in self.gradients])/len(self.gradients)
            delta=learning_rate*mean_gradient+momentum*self.previous_deltas[i]
            self.previous_deltas[i]=delta
            self.multiply_nodes[i].x[1]-=delta
        self.gradients = []  # ciscenje liste gradijenata (da sve bude cisto za sledecu iteraciju)

In [0]:
class NeuralLayer(ComputationalNode):

    def __init__(self, n_inputs, n_neurons, activation):
        self.n_inputs = n_inputs  # broj ulaza u ovaj sloj neurona
        self.n_neurons = n_neurons  # broj neurona u sloju (toliko ce biti i izlaza iz ovog sloja)
        self.activation = activation  # aktivaciona funkcija neurona u ovom sloju

        self.neurons = []
        # konstruisanje sloja nuerona
        for _ in range(n_neurons):
            neuron = NeuronNode(n_inputs, activation)
            self.neurons.append(neuron)

    def forward(self, x):  # x je vektor, odnosno lista "n_inputs" elemenata
        layer_output = []
        # forward-pass za sloj neurona je zapravo forward-pass za svaki neuron u sloju nad zadatim ulazom x
        for neuron in self.neurons:
            neuron_output = neuron.forward(x)
            layer_output.append(neuron_output)

        return layer_output

    def backward(self, dz):  # dz je vektor, odnosno lista "n_neurons" elemenata
        dd = []
        # backward-pass za sloj neurona je zapravo backward-pass za svaki neuron u sloju nad
        # zadatim spoljasnjim gradijentima dz
        print(dz[0])
        print(len(dz))
        print(enumerate(self.neurons))
        for i, neuron in enumerate(self.neurons):
            neuron_dz = [d[i] for d in dz]
            neuron_dz = neuron.backward(neuron_dz)
            dd.append(neuron_dz[:-1])  # izuzimamo gradijent za bias jer se on ne propagira unazad
        return dd

    def update_weights(self, learning_rate, momentum):
        # azuriranje tezina slojeva neurona je azuriranje tezina svakog neurona u tom sloju
        for neuron in self.neurons:
            neuron.update_weights(learning_rate, momentum)

In [0]:
class NeuralNetwork(ComputationalNode):

    def __init__(self):
        self.layers = []  # neuronska mreza se sastoji od slojeva neurona

    def add(self, layer):
        self.layers.append(layer)

    def forward(self, x):  # x je vektor koji predstavlja ulaz u neuronsku mrezu
        # TODO 9: implementirati forward-pass za celu neuronsku mrezu
        # ulaz za prvi sloj neurona je x
        # ulaz za sve ostale slojeve izlaz iz prethodnog sloja
        #raise NotImplementedError('TODO 9')
        prev_layer_output=None
        for idx, layer in enumerate(self.layers):
            if idx==0:
                prev_layer_output=layer.forward(x)
            else:
                prev_layer_output=layer.forward(prev_layer_output)
        return prev_layer_output

    def backward(self, dz):
        # TODO 10: implementirati forward-pass za celu neuronsku mrezu
        # spoljasnji gradijent za izlazni sloj neurona je dz
        # spoljasnji gradijenti za ostale slojeve su izracunati gradijenti iz sledeceg sloja
        #raise NotImplementedError('TODO 10')
        next_layer_dz=None
        for idx, layer in enumerate(self.layers[::-1]):
            if idx==0:
                next_layer_dz=layer.backward(dz)
            else:
                next_layer_dz=layer.backward(next_layer_dz)
        return next_layer_dz

    def update_weights(self, learning_rate, momentum):
        # azuriranje tezina neuronske mreze je azuriranje tezina slojeva
        for layer in self.layers:
            layer.update_weights(learning_rate, momentum)

    def fit(self, X, Y, learning_rate=0.1, momentum=0.0, nb_epochs=10, shuffle=False, verbose=0):
        assert len(X) == len(Y)

        hist = []  # za plotovanje funkcije greske kroz epohe
        for epoch in range(nb_epochs):

            if shuffle:  # izmesati podatke
                random.seed(epoch)
                random.shuffle(X)
                random.seed(epoch)
                random.shuffle(Y)

            total_loss = 0.0
            for x, y in zip(X, Y):
                y_pred = self.forward(x)  # forward-pass da izracunamo izlaz
                y_target = y  # zeljeni izlaz
                grad = 0.0
                for p, t in zip(y_pred, y_target):
                    total_loss += 0.5 * (t - p) ** 2.  # funkcija greske je kvadratna greska
                    grad += -(t - p)  # gradijent funkcije greske u odnosu na izlaz
                # backward-pass da izracunamo gradijente tezina
                self.backward([[grad]])
                # azuriranje tezina na osnovu izracunatih gradijenata i koraka "learning_rate"
                self.update_weights(learning_rate, momentum)

            if verbose == 1:
                print('Epoch {0}: loss {1}'.format(epoch + 1, total_loss))

            hist.append(total_loss)

        print('Loss: {0}'.format(total_loss))
        return hist

    def predict(self, x):
        return self.forward(x)

##Model

In [0]:
nn = NeuralNetwork()

nn.add(NeuralLayer(VOCAB_SIZE, VOCAB_SIZE, 'relu'))
nn.add(NeuralLayer(VOCAB_SIZE, 125, 'relu'))
nn.add(NeuralLayer(125, 25, 'relu'))
nn.add(NeuralLayer(25, 2, 'relu'))
print(train_vectors)
history = nn.fit(train_vectors, y_train, learning_rate=0.75, nb_epochs=3, shuffle=True)

In [0]:
del nn